feat(hw04): implement list
dndev-xx/go-os-std pull request #4
Opened 2024-10-25 22:54 UTC by dndev-xx

## Домашнее задание №4 «LRU-кэш»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я проверил, что все операции выполняются за О(1).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-10-27 07:04 UTC, vladislavmass requested changes

2024-10-27 07:04 UTC, vladislavmass commented on hw04_lru_cache/internal/libs/list.go
> +	mutex sync.Mutex
Абсолютно не нужная история для листа. У листа другая потокобезопасность. Если у нас есть лист из 3 элементов и мы одновременно будем добавлять 1 элемент в конец и один элемент в начало, то у нас не будет никаких проблем с потокобезопасностью. 

Этот подход актуален для структур которые хранят свои данные последовательно в неких областях памяти и когда участок памяти закончился необходимо выделить новый и скопировать туда данные,  лист же хранит свои элементы произвольно, поэтому у него другая степень потокобезопасности

2024-10-27 07:04 UTC, vladislavmass commented on hw04_lru_cache/test/cache_test.go
>  	t.Run("purge logic", func(t *testing.T) {
Хранить Unit Тесты в отдельном пакете очень плохая идея, так как тесты для своей работы должные иметь доступ в том числе к неэкспортируемым полям, а также если все тесты держать в одном пакете, то в конце это будет пакет в котором очень сложно ориентироваться

2024-10-27 09:10 UTC, dndev-xx commented on hw04_lru_cache/internal/libs/cache.go
> +		l.removeFromItems(lastRecently)
Непонятно как этого добиться, имея только значение

2024-10-27 09:11 UTC, dndev-xx commented on hw04_lru_cache/internal/libs/cache.go
> +	if l.queue.Len() > l.capacity {
Здесь ориентировался на алгоритм, который описан в ридми 
```
при добавлении элемента:
    - если элемент присутствует в словаре, то обновить его значение и переместить элемент в начало очереди;
    - если элемента нет в словаре, то добавить в словарь и в начало очереди
      (при этом, если размер очереди больше ёмкости кэша,
      то необходимо удалить последний элемент из очереди и его значение из словаря);
    - возвращаемое значение - флаг, присутствовал ли элемент в кэше.
```

2024-10-27 09:15 UTC, dndev-xx commented on hw04_lru_cache/test/cache_test.go
>  	t.Run("purge logic", func(t *testing.T) {
На практике же не желательно иметь доступ к неэкспортируемым полям - возможно для лучшего ориентира разбить в папке тест на подпапки по областям, тогда несложно будет ориентироваться
(Перенес папку тест в папку libs)

2024-10-29 11:09 UTC, vladislavmass commented on hw04_lru_cache/test/cache_test.go
>  	t.Run("purge logic", func(t *testing.T) {
Для Unit тестов иметь доступ ко внутренним полям структуры, которую тестирует это необходимая вещь.

2024-10-29 11:11 UTC, vladislavmass commented on hw04_lru_cache/internal/libs/cache.go
> +		l.removeFromItems(lastRecently)
Так у нас лист хранить any. Что мешает в эту any положит структуру где есть и ключ и значение. Фактически это прям указано в самом задание. `Элемент кэша хранит в себе ключ, по которому он лежит в словаре, и само значение.`

2024-10-29 11:12 UTC, vladislavmass approved these changes

2024-11-04 14:23 UTC, merged